### ISSUE TITLE
'git todo' command

### ISSUE THREAD

**Issue by jml** [jml/difftodo#16]
The old version of this tool had a `bzr todo` subcommand that was really quite handy. It would be nice to have a `git todo` command that by default showed all of the todos introduced in "this branch".

@jelmer informs me of the [tracking branch](http://git-scm.com/book/en/v2/Git-Branching-Remote-Branches#Tracking-Branches) concept in git, where you can use `git diff @{u}` to get a diff against the tracking branch.

Apparently adding a git subcommand is mostly just dropping a script in the correct directory.

**Comment by tomprince** [comment]
``` shell
 git config --global alias.todo '!git diff $(git merge-base origin HEAD) | diff-todo'
```
